/// Flutter icons MedicalRecordsIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MedicalRecordsIcons
///      fonts:
///       - asset: fonts/MedicalRecordsIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'MedicalRecordsIcons';
  static const _icAttachmentFontFam = 'ic_attachment';
  static const _kFontDevices = 'devices';
  static const _kFontBiotresDevices = 'biotres_device';
  static const String? _kFontPkg = null;

  static const IconData health_info =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData initial_Qol =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData demographic_info =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_attachment = IconData(0xe800,
      fontFamily: _icAttachmentFontFam, fontPackage: _kFontPkg);
  static const IconData ic_bioflux =
      IconData(0xe800, fontFamily: _kFontDevices, fontPackage: _kFontPkg);
  static const IconData ic_bioheart =
      IconData(0xe801, fontFamily: _kFontDevices, fontPackage: _kFontPkg);
  static const IconData ic_biotres = IconData(0xe800,
      fontFamily: _kFontBiotresDevices, fontPackage: _kFontPkg);
}
