name: Analyze, Format-check and Test

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ dev ]

jobs:
  analyze-and-test:
    name: Analyze, Format-check and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6'

      - name: Flutter --version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze
