name: CI

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ dev ]

jobs:
  analyze-and-test:
    name: Analyze, Format-check and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      - name: Flutter --version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Dart format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze
